#!/bin/bash
# ---------------------------------------------------------------------
# optimization_report.sh
#
# Generates assembly (.s) output for every source file at -O0, -O1,
# -O2, and -O3, measures each file's size, and produces a comparison
# report (optimization_report.md). Assumes all .c/.h files sit in the
# current directory (flat layout, no src/include subfolders).
#
# Usage: bash optimization_report.sh
# ---------------------------------------------------------------------
set -e

SRC_FILES="main.c globals.c utility.c notification.c authentication.c persistence.c income.c expense.c transaction.c budget.c savings_goal.c dashboard.c reports.c recommendation.c investment.c category_index.c activity_log.c logger.c autosave.c sha256.c"

LEVELS="O0 O1 O2 O3"

rm -rf asm
mkdir -p asm/O0 asm/O1 asm/O2 asm/O3

REPORT=optimization_report.md

{
  echo "# Optimization report"
  echo
  echo "Generated by optimization_report.sh. Assembly size is the byte"
  echo "size of the .s file GCC emits with -S at each optimization level"
  echo "(source -> assembly, no linking). Binary size is text/data/bss"
  echo "of the fully linked finance executable at the same level."
  echo
  echo "## Per-file assembly size (bytes)"
  echo
  echo "| File | -O0 | -O1 | -O2 | -O3 | O0->O3 change |"
  echo "|---|---:|---:|---:|---:|---:|"
} > "$REPORT"

TOTAL_O0=0
TOTAL_O1=0
TOTAL_O2=0
TOTAL_O3=0

for f in $SRC_FILES; do
  base=$(basename "$f" .c)
  row="| $f "
  declare -A sizes
  for lvl in $LEVELS; do
    gcc -"$lvl" -Wall -Wextra -pthread -S "$f" -o "asm/$lvl/$base.s"
    sz=$(wc -c < "asm/$lvl/$base.s")
    sizes[$lvl]=$sz
    row="$row| $sz "
  done
  TOTAL_O0=$((TOTAL_O0 + sizes[O0]))
  TOTAL_O1=$((TOTAL_O1 + sizes[O1]))
  TOTAL_O2=$((TOTAL_O2 + sizes[O2]))
  TOTAL_O3=$((TOTAL_O3 + sizes[O3]))
  if [ "${sizes[O0]}" -gt 0 ]; then
    pct=$(( (sizes[O3] - sizes[O0]) * 100 / sizes[O0] ))
  else
    pct=0
  fi
  row="$row| ${pct}% |"
  echo "$row" >> "$REPORT"
  unset sizes
done

pct_total=$(( (TOTAL_O3 - TOTAL_O0) * 100 / TOTAL_O0 ))
{
  echo "| **Total** | **$TOTAL_O0** | **$TOTAL_O1** | **$TOTAL_O2** | **$TOTAL_O3** | **${pct_total}%** |"
  echo
  echo "## Linked binary size (bytes) - size text/data/bss"
  echo
  echo "| Level | text | data | bss | total |"
  echo "|---|---:|---:|---:|---:|"
} >> "$REPORT"

for lvl in $LEVELS; do
  gcc -"$lvl" -Wall -Wextra -pthread $SRC_FILES -o "finance_$lvl"
  read -r t d b dec _ <<< "$(size finance_"$lvl" | tail -1)"
  echo "| -$lvl | $t | $d | $b | $dec |" >> "$REPORT"
  rm -f "finance_$lvl"
done

echo >> "$REPORT"
echo "Assembly files are kept under asm/O0 .. asm/O3 for inspection." >> "$REPORT"

echo "Report written to $REPORT"
cat "$REPORT"
